# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SE_wjtkQ5Mls0npgHyN1WCrMTenH0yKU
"""

# WEEK 2
# SECTION A
#1
def sum_three(a,b,c):
 if a==b or b==c or c==a:
   sum=3
 else:
   sum=3
 return sum
print(sum_three(4,6,8))
print(sum_three(3,2,1))

#2
def DtoLoT(dict):
    dict = {'RISHABH':10, 'SAMAR':15, 'MAHI':25, 'PRAGATI':45}
    list = [(k, v) for k, v in dict.items()]

    list.sort(key = lambda x: x[0])
    return list

print(DtoLoT(dict))

#3
def replaceVowels(str, K):
    vowels = 'aeiou'
    for i in vowels:
        str = str.replace(i, K)
    return str

input_str = "mai hu ek udta robo ,doraemon"
K = "i"

print("Input string =", input_str)
print("Specified vowel =", K)
print("After replacing =", replaceVowels(input_str, K))

#4
#def function3(str):
Munna  = "haar kar jeetne wale ko bajigar kahte hain.."
z = list(Munna)
print(z)
go = []
for i in z:
    go.extend(ord(num) for num in i)
print(go)


odd = []
even = []
for i in go:
    if(i % 2 ==0):
        even.append(i)
    else:
        odd.append(i)

#5
def khesari(st):
  res = []
  for index, c in enumerate(st):
    if index % 2 == 0:
      res.append(c.upper())
    else:
      res.append(c.lower())
  return '' .join(res)
print(khesari("if you know you know ."))

# SECTION B
#1
def factorial(n):
     
    
    return 1 if (n==1 or n==0) else n * factorial(n - 1);
 

num = 20;
print("Factorial of",num,"is",
factorial(num))

#2
def myfunction():
    print("somthing went wrong")
myfunction()

#3

def largest_num_in_list( list ):
    max = list[ 0 ]
    for a in list:
        if a > max:
            max = a
    return max
print(largest_num_in_list([10, 15, 25, 30]))

#4

def test_prime(n):
    if (n==1):
        return False
    elif (n==2):
        return True;
    else:
        for x in range(2,n):
            if(n % x==0):
                return False
        return True             
print(test_prime(29))

#5
def is_even_num(l):
    evennum = []
    for n in l:
        if n % 2 == 0:
            evennum.append(n)
    return evennum
print(is_even_num([26,14,25,368,152,748,245,152]))